In [1]:
# Let's read in our document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('dtm_stop.pkl')
data

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abject,...,zee,zen,zeppelin,zero,zillion,zombie,zombies,zoning,zoo,éclair
ali,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,1,1,1,1,0,0
bo,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,2,1,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,3,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0

In [33]:
# Import the necessary modules for LDA with gensim
# Terminal / Anaconda Navigator: conda install -c conda-forge gensim
from gensim import matutils, models
import scipy.sparse

# import logging
# logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [34]:
# One of the required inputs is a term-document matrix
tdm = data.transpose()
tdm.head()

,ali,anthony,bill,bo,dave,hasan,jim,joe,john,louis,mike,ricky
aaaaah,0,0,1,0,0,0,0,0,0,0,0,0
aaaaahhhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaaauuugghhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaahhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaah,0,0,0,0,1,0,0,0,0,0,0,0

In [35]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [36]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

In [37]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.006*"says" + 0.005*"cause" + 0.004*"jenny" + 0.004*"goes" + 0.004*"really" + 0.004*"id" + 0.004*"mean" + 0.004*"point" + 0.003*"kind" + 0.003*"uh"'),
 (1,
  '0.008*"fucking" + 0.007*"shit" + 0.006*"fuck" + 0.006*"say" + 0.005*"theyre" + 0.005*"going" + 0.005*"hes" + 0.005*"want" + 0.005*"didnt" + 0.005*"thing"')]

In [38]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.010*"fucking" + 0.009*"shit" + 0.006*"fuck" + 0.006*"want" + 0.006*"didnt" + 0.005*"man" + 0.005*"hes" + 0.005*"did" + 0.005*"love" + 0.004*"good"'),
 (1,
  '0.006*"went" + 0.006*"say" + 0.006*"fucking" + 0.006*"thing" + 0.006*"day" + 0.006*"cause" + 0.005*"theyre" + 0.005*"going" + 0.005*"really" + 0.005*"didnt"'),
 (2,
  '0.007*"fuck" + 0.007*"shit" + 0.006*"fucking" + 0.006*"theyre" + 0.005*"going" + 0.005*"dad" + 0.005*"want" + 0.005*"say" + 0.004*"white" + 0.004*"shes"')]

In [39]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.007*"fucking" + 0.006*"cause" + 0.006*"went" + 0.006*"day" + 0.006*"goes" + 0.005*"going" + 0.005*"really" + 0.005*"says" + 0.005*"theyre" + 0.004*"shit"'),
 (1,
  '0.008*"fucking" + 0.007*"say" + 0.007*"went" + 0.006*"id" + 0.005*"didnt" + 0.005*"little" + 0.005*"joke" + 0.005*"theyre" + 0.005*"hes" + 0.005*"ive"'),
 (2,
  '0.008*"fucking" + 0.007*"shit" + 0.007*"fuck" + 0.006*"say" + 0.005*"want" + 0.005*"didnt" + 0.005*"theyre" + 0.005*"hes" + 0.005*"life" + 0.005*"going"'),
 (3,
  '0.001*"fucking" + 0.000*"shit" + 0.000*"say" + 0.000*"little" + 0.000*"theyre" + 0.000*"day" + 0.000*"went" + 0.000*"fuck" + 0.000*"want" + 0.000*"ive"')]

In [40]:
# Topic Modeling - Attempt #2 (Nouns Only)
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [41]:
# Read in the cleaned data, before the CountVectorizer step
data_clean = pd.read_pickle('data_clean.pkl')
data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
bo       bo what old macdonald had a farm e i e i o and...
dave     this is dave he tells dirty jokes for a living...
hasan      whats up davis whats up im home i had to bri...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
john     all right petunia wish me luck out there you w...
louis    introfade the music out lets roll hold there l...
mike     wow hey thank you thanks thank you guys hey se...
ricky    hello hello how you doing great thank you wow ...

In [42]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
bo       macdonald farm e i o farm pig e i i snort macd...
dave     jokes living stare work profound train thought...
hasan    whats davis whats home i netflix la york i son...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fuck thanks phone fuckfac...
john     petunia thats hello hello chicago thank crowd ...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
ricky    hello thank fuck thank im gon youre weve money...

In [43]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abortion,abortions,abuse,...,yummy,ze,zealand,zee,zeppelin,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,2,0,0,...,0,0,10,0,0,0,0,0,0,0
bill,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,1,1,0,0
bo,1,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [44]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [45]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.010*"day" + 0.008*"thing" + 0.006*"shit" + 0.006*"way" + 0.006*"joke" + 0.006*"man" + 0.006*"lot" + 0.006*"things" + 0.006*"cause" + 0.005*"house"'),
 (1,
  '0.009*"thing" + 0.008*"shit" + 0.008*"life" + 0.008*"man" + 0.008*"hes" + 0.007*"day" + 0.007*"guy" + 0.006*"cause" + 0.006*"way" + 0.006*"fuck"')]

In [46]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.011*"shit" + 0.009*"lot" + 0.008*"life" + 0.008*"man" + 0.008*"thing" + 0.007*"day" + 0.007*"hes" + 0.007*"women" + 0.006*"way" + 0.006*"cause"'),
 (1,
  '0.010*"thing" + 0.009*"day" + 0.009*"fuck" + 0.008*"shit" + 0.008*"man" + 0.008*"life" + 0.008*"hes" + 0.006*"shes" + 0.006*"guy" + 0.006*"dad"'),
 (2,
  '0.008*"cause" + 0.008*"way" + 0.007*"day" + 0.006*"kind" + 0.006*"point" + 0.006*"night" + 0.006*"clinton" + 0.005*"thing" + 0.005*"house" + 0.005*"hey"')]

In [47]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.013*"fuck" + 0.010*"man" + 0.009*"house" + 0.009*"shit" + 0.008*"kids" + 0.007*"life" + 0.007*"theyre" + 0.007*"cause" + 0.007*"gon" + 0.007*"things"'),
 (1,
  '0.012*"thing" + 0.010*"day" + 0.009*"life" + 0.009*"hes" + 0.008*"cause" + 0.007*"gon" + 0.007*"guy" + 0.007*"way" + 0.007*"joke" + 0.007*"shit"'),
 (2,
  '0.011*"dad" + 0.007*"mom" + 0.007*"way" + 0.007*"life" + 0.007*"man" + 0.007*"shes" + 0.006*"day" + 0.006*"hes" + 0.006*"hey" + 0.006*"parents"'),
 (3,
  '0.012*"shit" + 0.010*"day" + 0.010*"lot" + 0.010*"women" + 0.010*"man" + 0.009*"fuck" + 0.008*"thing" + 0.007*"cause" + 0.006*"guy" + 0.006*"hes"')]

In [48]:
# Topic Modeling - Attempt #3 (Nouns and Adjectives)
# Let's create a function to pull out nouns from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [49]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                transcript
ali      ladies gentlemen welcome stage ali wong hi wel...
anthony  thank san francisco thank good people surprise...
bill     right thank thank pleasure greater atlanta geo...
bo       old macdonald farm e i i o farm pig e i i snor...
dave     dirty jokes living stare most hard work profou...
hasan    whats davis whats im home i netflix special la...
jim      ladies gentlemen welcome stage mr jim jefferie...
joe      ladies gentlemen joe fuck san francisco thanks...
john     right petunia august thats good right hello he...
louis    music lets lights lights thank much i i i nice...
mike     wow hey thanks hey seattle nice look crazy ins...
ricky    hello great thank fuck thank lovely welcome im...

In [50]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abject,able,...,ze,zealand,zee,zeppelin,zero,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,1,0,0
bo,0,1,1,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,3,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,1,1,2,...,0,0,0,0,0,0,0,0,1,0

In [51]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [52]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.007*"joke" + 0.003*"ok" + 0.003*"jokes" + 0.003*"bo" + 0.003*"dead" + 0.003*"repeat" + 0.003*"eye" + 0.002*"hell" + 0.002*"nuts" + 0.002*"anthony"'),
 (1,
  '0.004*"mom" + 0.004*"parents" + 0.003*"friend" + 0.003*"door" + 0.003*"son" + 0.003*"ass" + 0.003*"wife" + 0.002*"class" + 0.002*"hasan" + 0.002*"dick"')]

In [53]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.006*"bo" + 0.006*"hasan" + 0.005*"repeat" + 0.005*"mom" + 0.005*"contact" + 0.004*"eye" + 0.004*"comedy" + 0.004*"parents" + 0.004*"brown" + 0.004*"cos"'),
 (1,
  '0.004*"jenny" + 0.004*"ahah" + 0.003*"gay" + 0.003*"friend" + 0.003*"tit" + 0.003*"son" + 0.003*"morning" + 0.002*"young" + 0.002*"nigga" + 0.002*"gun"'),
 (2,
  '0.006*"joke" + 0.005*"mom" + 0.004*"ass" + 0.003*"jokes" + 0.003*"guns" + 0.003*"clinton" + 0.002*"parents" + 0.002*"dick" + 0.002*"anthony" + 0.002*"friend"')]

In [54]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.008*"joke" + 0.006*"anthony" + 0.005*"jokes" + 0.005*"mom" + 0.004*"mad" + 0.004*"grandma" + 0.004*"stupid" + 0.004*"san" + 0.004*"shark" + 0.003*"dick"'),
 (1,
  '0.006*"joke" + 0.003*"nuts" + 0.003*"hell" + 0.003*"husband" + 0.003*"dead" + 0.003*"ok" + 0.003*"jenner" + 0.003*"gun" + 0.003*"doctor" + 0.002*"ass"'),
 (2,
  '0.004*"bo" + 0.004*"son" + 0.004*"hasan" + 0.004*"repeat" + 0.004*"um" + 0.004*"ahah" + 0.003*"comedy" + 0.003*"guns" + 0.003*"gay" + 0.003*"mom"'),
 (3,
  '0.005*"parents" + 0.005*"jenny" + 0.005*"clinton" + 0.004*"friend" + 0.004*"mom" + 0.004*"tit" + 0.004*"cow" + 0.003*"dog" + 0.003*"idea" + 0.003*"wife"')]

In [55]:
# Identify Topics in Each Document
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.000*"lights" + 0.000*"write" + 0.000*"pieces" + 0.000*"firefighter" + 0.000*"uncomfortable" + 0.000*"art" + 0.000*"wipe" + 0.000*"gorgeous" + 0.000*"happens" + 0.000*"powers"'),
 (1,
  '0.006*"bo" + 0.005*"repeat" + 0.005*"ahah" + 0.005*"um" + 0.005*"guns" + 0.004*"son" + 0.004*"gay" + 0.004*"eye" + 0.004*"contact" + 0.003*"ass"'),
 (2,
  '0.007*"joke" + 0.005*"mom" + 0.003*"jokes" + 0.003*"clinton" + 0.003*"hell" + 0.003*"wife" + 0.003*"parents" + 0.003*"dead" + 0.003*"dick" + 0.003*"ass"'),
 (3,
  '0.006*"parents" + 0.005*"hasan" + 0.005*"jenny" + 0.004*"mom" + 0.004*"york" + 0.004*"tit" + 0.003*"date" + 0.003*"brown" + 0.003*"love" + 0.003*"door"')]

In [56]:
# Let's take a look at which topics each transcript contains
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(2, 'ali'),
 (2, 'anthony'),
 (2, 'bill'),
 (1, 'bo'),
 (1, 'dave'),
 (3, 'hasan'),
 (1, 'jim'),
 (2, 'joe'),
 (2, 'john'),
 (3, 'louis'),
 (3, 'mike'),
 (2, 'ricky')]